### ISSUE TITLE
Signature events

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform#2310]
This issue is to summarize the events that should happen when a submission is signed. Each of should likely have a new issue created to provide more details.

- [x] Collect and store TS data in a table #2363
- [x] Collect and store LAR data in a table #2342
- [x] IRS report #2343
- [x] Modified LAR #2341 
- [x] Set the HMDA filer flag to `true` #2344
- [x] Create and save, to an S3 bucket, the regulator data #2312
