### ISSUE TITLE
Validation (2017): Syntactical edit checks

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-platform#32]
- [ ]  Transmittal sheet (TS) & Loan Application Register (LAR) #33 
- [ ] Transmittal sheet (TS) only #39 
- [ ] Loan Application Register (LAR) only #43
