### ISSUE TITLE
Test new 2020 Edits

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-platform#3475]
Test edits that are new for 2020 on beta

- [x] [S306](https://github.com/cfpb/hmda-platform/issues/3204) - Works as expected!
- [x] [V716](https://github.com/cfpb/hmda-platform/issues/3206) - V716 will not be in the quarterly filing platform. Will not test until later this year.
- [x] [V717](https://github.com/cfpb/hmda-platform/issues/3203) - Works as expected!
- [x] [V718](https://github.com/cfpb/hmda-platform/issues/3200) - Works as expected

_These edits will be retested once the edit report tables are shown._ 

- [x] [Q606](https://github.com/cfpb/hmda-platform/issues/3207) - Works as expected. 
- [x] [Q614](https://github.com/cfpb/hmda-platform/issues/3208) - Q614-1 Works as expected. Q614-2 Works as expected. 
- [x] [Q617](https://github.com/cfpb/hmda-platform/issues/3209) - Edit description needs to be updated - If Combined Loan-to-Value Ratio and Property Value are not reported Exempt or NA, then the Combined Loan-to Value Ratio generally should be greater than or equal to the Loan-to-Value Ratio (calculated as Loan Amount divided by the Property Value). should be **If Loan Type equals 1 and** Combined Loan-to-Value Ratio and Property Value are not reported NA or Exempt, then the Combined Loan-to Value Ratio generally should be greater than or equal to the Loan to-Value Ratio (calculated as Loan Amount divided by the Property Value).

- [x] [Q648](https://github.com/cfpb/hmda-platform/issues/3210) - Works as expected. 
- [x] [Q649](https://github.com/cfpb/hmda-platform/issues/3211) - Q649-1 Works as expected. Q649-2 Works as expected. 
- [x] [Q650](https://github.com/cfpb/hmda-platform/issues/3212) - Works as expected. 
- [x] [Q651](https://github.com/cfpb/hmda-platform/issues/3213) - Works as expected. 
- [x] [Q652](https://github.com/cfpb/hmda-platform/issues/3214) - Works as expected. 
- [x] [Q653](https://github.com/cfpb/hmda-platform/issues/3215) - Q653-1 Works as expected. Q653-2 Works as expected. 
- [x] [Q654](https://github.com/cfpb/hmda-platform/issues/3216) - Works as expected.

**Comment by chynnakeys** [comment]
Missing edit descriptions for Q648 & Q651 
![image](https://user-images.githubusercontent.com/41752348/75198226-18898800-572e-11ea-8d9d-b17ed13b793d.png)

**Comment by chynnakeys** [comment]
S306 is not triggering. Test file: 
[Chynna Bank_s306_5_rows.txt](https://github.com/cfpb/hmda-platform/files/4344650/Chynna.Bank_s306_5_rows.txt)

**Comment by chynnakeys** [comment]
V717 is showing and error field mismatch message
![image](https://user-images.githubusercontent.com/41752348/76893867-7740ae00-6863-11ea-8d4e-c425215608d9.png)

[Chynna Bank_500_v717_b.txt](https://github.com/cfpb/hmda-platform/files/4345399/Chynna.Bank_500_v717_b.txt)

**Comment by chynnakeys** [comment]
Q614-1 and Q614-2 do not show the edit description 
![image](https://user-images.githubusercontent.com/41752348/76903152-d9091400-6873-11ea-9810-f6319312268f.png)

**Comment by chynnakeys** [comment]
Q617 Edit description needs to be updated: should be If Loan Type equals 1 and Combined Loan-to-Value Ratio and Property Value are not reported NA or Exempt, then the Combined Loan-to Value Ratio generally should be greater than or equal to the Loan to-Value Ratio (calculated as Loan Amount divided by the Property Value).

![image](https://user-images.githubusercontent.com/41752348/76903593-b0354e80-6874-11ea-8b3b-7a915afba8f2.png)

**Comment by chynnakeys** [comment]
Q648 edit description and related data fields missing (Action Taken, LEI, ULI)
![image](https://user-images.githubusercontent.com/41752348/76903890-3a7db280-6875-11ea-9999-577241de1e0f.png)

**Comment by chynnakeys** [comment]
Q649-654 all missing the edit descriptions and related data fields
![image](https://user-images.githubusercontent.com/41752348/76904069-a102d080-6875-11ea-9ea9-64177be0c00b.png)
![image](https://user-images.githubusercontent.com/41752348/76904217-ee7f3d80-6875-11ea-83a5-5a010eafdf52.png)
![image](https://user-images.githubusercontent.com/41752348/76904353-2b4b3480-6876-11ea-848b-6c1a5e2701db.png)

**Comment by chynnakeys** [comment]
@BarakStout Can you please add the edit logic for S306: 
Edit Logic:
If Action Taken equals 1, a duplicate ULI cannot be reported

![image](https://user-images.githubusercontent.com/41752348/77179178-80698f00-6a9e-11ea-93ad-74d8c803f7a9.png)

**Comment by chynnakeys** [comment]
@BarakStout for Q648, can you only show the ULI once? it's showing twice 
![image](https://user-images.githubusercontent.com/41752348/77187013-35557900-6aaa-11ea-910d-9f0ee44372c9.png)

**Comment by chynnakeys** [comment]
@BarakStout for Q649-2 the second label should be for the age of co-applicant, not applicant

![image](https://user-images.githubusercontent.com/41752348/77203478-dd793b00-6ac6-11ea-9fc5-a8f555b95022.png)

**Comment by BarakStout** [comment]
Q648 and Q649-2 updated via #3544 

S306 will be fixed with #3528
