### ISSUE TITLE
Test 2022 Edits

### ISSUE THREAD

**Issue by audayshankar** [cfpb/hmda-platform#4297]
- [x] S307
- [x] V608
- [x] V660
- [x] V662-1 - Found issue, see [comment](https://github.com/cfpb/hmda-platform/issues/4297#issuecomment-984767804) below
- [x] V665-2 - Found issue, see [comment](https://github.com/cfpb/hmda-platform/issues/4297#issuecomment-984760246) below
- [x] V667-1 - Suggestion to improve edit, see [comment](https://github.com/cfpb/hmda-platform/issues/4297#issuecomment-984783749)
- [x] V720
- [x] V721
- [x] Q654
- [x] Q658
- [x] Q659

**Comment by audayshankar** [comment]
2022 is not appearing as on option on HMDA Help dropdown (dev environment) to add institutions for testing. @meissadia 
![image](https://user-images.githubusercontent.com/58990254/144125931-f445627e-9396-4fb9-8625-12ed67aff9c3.png)

**Comment by audayshankar** [comment]
V662-1 should not be triggering in this case, since _Applicant or Borrower, Name and Version of Credit Scoring Model_ equals 11 and the _Applicant or Borrower, Name and Version of Credit Scoring Model: Conditional Free Form Text Field for Code 8_ field is blank.  
[Chynna Bank_V662_prod.txt](https://github.com/cfpb/hmda-platform/files/7643325/Chynna.Bank_V662_prod.txt)

![image](https://user-images.githubusercontent.com/58990254/144457577-181f7885-01fd-42ba-a930-ded3d84037cb.png)

When trying to trigger V662-2, both V662-2 and V662-1 triggered which should not be possible
[Chynna Bank_V662-2.txt](https://github.com/cfpb/hmda-platform/files/7643342/Chynna.Bank_V662-2.txt)

![image](https://user-images.githubusercontent.com/58990254/144458394-f7142176-fc90-47e2-b7ff-5c0581a1701e.png)

**Comment by audayshankar** [comment]
Suggestion (not error) - Applies to V662 and V667

We should consider replacing "the reverse is true" with actually writing out the sentence to minimize confusion.

Example Correction:
If Co-Applicant or Co-Borrower, Name and Version of Credit Scoring Model equals 8, then Co-Applicant or Co-Borrower, Name and Version of Credit Scoring Model: Conditional Free Form Text Field for Code 8 must not be left blank, and the reverse must be true.

 _If Co-Applicant or Co-Borrower, Name and Version of Credit Scoring Model: Conditional Free Form Text Field for Code 8 is not left blank, Co-Applicant or Co-Borrower, Name and Version of Credit Scoring Model must equal 8_

![image](https://user-images.githubusercontent.com/58990254/144460240-ca2a7b07-7b76-4cfe-8b5f-e18632d48301.png)

**Comment by audayshankar** [comment]
Triggering V662-2 also triggers V662-1 and for some reason, it causes a loading error. 
![image](https://user-images.githubusercontent.com/58990254/144886777-ea11c02d-6825-492f-bccc-e2cbf3be752a.png)

Eventually the platform, loads but results in this error
![image](https://user-images.githubusercontent.com/58990254/144886839-62029465-ec76-4fc7-9075-76cdb068be72.png)

The edit report is accurate once you download, but I haven't seen this happen before. Is there something here we can correct? @kgudel
